### ISSUE TITLE
Unpin pip dependencies that don't need to be pinned

### ISSUE THREAD

**Issue by stvnrlly** [GSA/notifications-api#103]

**Comment by terrazoon** [comment]
Do we want to unpin stuff, or do we want to create a dependabot task to create PRs for us with updates?

Dependabot will create some PR clutter, but then we can always rollback to a working version.  Whereas if we unpin a lot of things ...

**Comment by stvnrlly** [comment]
Maybe both? I think our first step is to run through the dependencies and see what can be upgraded, and how close to the latest version we can get. That might require code updates on our end, too.

After that, we can set up some Dependabot tasks (in addition to our security ones) to help us stay current.

**Comment by terrazoon** [comment]
Okay, so I tried updating the Pipfile by using '*' wherever I could and it first it seemed all right.  Tests would still pass and the UI still came up.  But upon closer inspection there were actually a lot of strange errors in the notifications-api logs, and sms messages stopped being sent.   So I have closed the two PRs that I did originally.

I think it is considered a best practice to pin everything, because that way you are documenting "at least this configuration works".    What I would recommend is to set up Dependabot first, let it generate upgrade PRs, and do the upgrades one at a time (always testing etc).

I think trying to upgrade to latest in one fell swoop is not going to go well.
