### ISSUE TITLE
Exception Investigation:  builtins:ValueError

### ISSUE THREAD

**Issue by ccostino** [GSA/notifications-api#1142]
This is one of the errors we've seen captured in New Relic that we'd like to dig into and understand, if not also resolve.

**Error message:**
A string literal cannot contain NUL (0x00) characters.
Path: /service/XXXXXXX/notifications
Transaction name: WebTransaction/Function/app.service.rest:get_all_notifications_for_service
Exception:  builtins:ValueError

No stack trace available; see the information above.

## Implementation Sketch and Acceptance Criteria

- [ ] Look through our log history at https://logs.fr.cloud.gov/ and see if any patterns emerge that might indicate what conditions cause this
- [ ] Try and replicate the error, if possible
- [ ] Follow up in this issue with any findings and possible remediation steps

## Security Considerations

- Be mindful of not sharing sensitive information.
- We'd like to reduce the errors that occur in the application where possible to maintain application stability and performance, and reduce the chances that the application ends up in an error or invalid state.

**Comment by terrazoon** [comment]
This particular error happened during a one hour time period on June 16th, 2024.  At the time it was happening we also saw many hundreds of these:

[ERROR] Worker (pid:360617) was sent SIGKILL! Perhaps out of memory?"

I think due to being out of memory, it was unable to set the task name, which was null according to the log messages.

Unless this reoccurs in the future, I would assume it is due to memory issues and should be resolved.

**Comment by ccostino** [comment]
This makes sense to me!  We'll keep an eye out for future occurrences now that we've done some memory bumps and increased the worker instance count as well.
