### ISSUE TITLE
Research the proper amount of workers and RAM (memory) per worker for Celery

### ISSUE THREAD

**Issue by ccostino** [GSA/notifications-api#1390]
We've been running into several performance and scaling issues in our production environment lately that are related to sending messages and retrieving their status (or the reports).  All of this seems to stem from the fact that we did not have enough RAM (memory) available for our existing workers, and not enough worker processes available in general.

We recently made a couple of adjustments to account for this:

* https://github.com/GSA/notifications-api/pull/1384
* https://github.com/GSA/notifications-api/pull/1387

And it would seem we may even need to increase memory and worker process count a bit more, but that's not entirely clear just yet.  Before we do that, we'd like to know if there's a formula or method for determining what an appropriate number for each would be.  This is likely dependent on our average usage load and what we anticipate our highest spikes will be, but it'd be nice to know if there was a general recommendation for what's best or what usage patterns to monitor to help make a determination.

At the moment the memory usage for the 4 worker processes in production is roughly 1.2 GB out of 3 GB total, so it seems to be spread pretty evenly now, but it'd be nice to know for sure if this is ideal with a bit of room to grow and/or account for spikes.

## Implementation Sketch and Acceptance Criteria

- [ ] Look into how best to configure Celery worker processes and balancing resource usage with performance and stability.
- [ ] Do some investigative research on how our app is behaving based on its current configuration vs. what appears to be recommended
- [ ] Propose any changes that would be beneficial for us; if we end up needing more memory in cloud.gov then so be it!

## Security Considerations

- We want to make sure our application is stable and functioning properly to prevent any undesirable side effects or errors from happening that could put it in a vulnerable state.

**Comment by ccostino** [comment]
The [Celery Optimization Guide](https://docs.celeryq.dev/en/stable/userguide/optimizing.html#guide-optimizing) is a good place to start for this.

**Comment by terrazoon** [comment]
1.  We are using --concurrency 4 and have 4 cores on production.  Allocating one worker per core is considered best practice so we are good there.

2. From googling, it sounds like celery workers performing "moderate tasks" (i.e. JSON processing, let's say, not imaging processing) require 300 mb to 500 mb memory each.  So with 3 GB memory allocated to the app, we seem to be following best practice here as well with our recent memory increases.

3. We are using 'prefork' pool support, which is the default, and which is also a best practice for all-purpose applications with no specific needs.

4. Because we are using 'prefork' we are able to specify worker-max-tasks-per-child to 200, which will kill off each worker when it performs 200 tasks and create a new worker.  This is a best practice to guard against memory leaks and connection leaks.

A lot of this is from googling.  The actually celery docs are slightly cryptic, but here are some:

prefork pool support is best:  https://docs.celeryq.dev/en/stable/userguide/concurrency/index.html

use worker-max-tasks-per-child:
https://docs.celeryq.dev/en/stable/userguide/optimizing.html

**Comment by terrazoon** [comment]
There is also a worker-max-memory-per-child setting which will restart a worker if it exceeds a certain amount of memory.  I think it is not advisable to use this setting, because then we will have to actively monitor workers.  At this time we also do not think there is some unique, weird task with a huge memory requirement that is destabilizing things, but rather we suffer a gradual leak of either memory or connects.  So worker-max-tasks-per-child is a more agnostic way to stabilize things.

**Comment by terrazoon** [comment]
Assuming 200 mb for the cache, and 4 * 500 mb for the workers, our 3 GB memory limit looks a bit tight.  I would recommend increasing total memory to 4 GB.

**Comment by terrazoon** [comment]
Finished!
