### ISSUE TITLE
Increase code coverage to 95%

### ISSUE THREAD

**Issue by stvnrlly** [GSA/notifications-api#391]

**Comment by terrazoon** [comment]
In working on this, I noticed that tests that passed on my local failed remotely.  I think I have tracked this down to the GitHub workflow, which is assigning four workers when the pytests run.  The issue is that we have multiple db-related tests running simultaneously (remotely) which puts the db in an inconsistent state relative to the local tests.

This might make remote tests a lot slower, maybe we can bump up the size of the container or something if that is the case.
