### ISSUE TITLE
Lock accounts for 30 minutes after 10 failed login attempts in 30 minutes

### ISSUE THREAD

**Issue by stvnrlly** [GSA/notifications-api#513]
AC-8 requires that 10 failed login attempts within 30 minutes results in a 30-minute account lock.

To complete in API:
- [ ] Add logic to count failed logins
- [ ] Add logic to lock account if limit is tripped, then unlock

To complete in UI:
- [ ] Show user remaining attempts after failed login
- [ ] Show user an error message if their account is locked

**Comment by terrazoon** [comment]
Is this still relevant if we are moving to login.gov?

**Comment by terrazoon** [comment]
Need some clarification about what this means in a post-login.gov world.

1. User clicks on 'sign in' and is redirected to login.gov
2. User enters valid login.gov credentials
3. User is redirected to our app
4. Our app does not find the user (by email) who is trying to log in, presumably because they were never invited to join.

Is this a failed login and subject to the logic above (I assume yes)?

**Comment by terrazoon** [comment]
Is this still relevant?  What would it mean in the context of working with login.gov?

**Comment by terrazoon** [comment]
As per @stvnrlly this is an explicit responsibility of login.gov in our sspp, so closing as there is nothing for us to do, being already integrated with login.gov.
