### ISSUE TITLE
Remove Phone Numbers Epic

### ISSUE THREAD

**Issue by ccostino** [GSA/notifications-api#667]
Issue originally written by @terrazoon:

- rewrite one-off sends so they are jobs too.  Any message send should be a job. (https://github.com/GSA/notifications-admin/issues/1035)

- Change report logic to pull from csv file if redis doesn't have it for any reason. (https://github.com/GSA/notifications-admin/issues/1051)
- remove phone number column from notifications and notifications_history (https://github.com/GSA/notifications-api/issues/742)
- remove personalization from notifications (https://github.com/GSA/notifications-api/issues/749)

**Comment by ccostino** [comment]
In the case of converting the processing of instant sends to mirror the full CSV processing, we may be able to do something like leveraging [`NamedTemporaryFile`](https://docs.python.org/3.9/library/tempfile.html#tempfile.NamedTemporaryFile) to create something that exists only while the send flow is happening for the one-off send.

Even better if we can just do it in memory with something like a file stream (e.g., [`StringIO`](https://docs.python.org/3.9/library/io.html#io.StringIO) since a CSV writer just needs a file-like object to write to (and same for a CSV reader), but if we find that we need to create a file, just generating a temporary one that goes away after the send is done may be enough.

The other thing to consider is the use case and workflow of the one-off send - off the top of my head I'm not sure if we're storing a record or the same info as we do for a CSV batch job.  If we are, then this makes more sense to mirror the processing.  If we're not, then that's something else to explore a bit further to see if we should be treating it the same way or not.

**Comment by terrazoon** [comment]
Steven's recommendation:

1. get rid of notifications/notification_history table in favor of notification_all_time_view
2. add a new queued status for notifications
3. when processing csv, immediately add anonymized version to that table with queued status
4. add 2 more columns, csv_file and csv_row, to allow us to find the data if we need to
5. add the message data previously temporarily stored in db to redis for ease of job handling (if it isn't already there)
6. add a batch_id for each message, so that we can quickly filter data for each individual batch of messages

Note that #6 already exists in the form of job_id in the notification table.

**Comment by stvnrlly** [comment]
Okay, a fresh revision of the overarching plan.

Step one // create a sending path that works without saving PII to database

- Update `deliver_sms` to receive the encrypted data used by `save_sms` to persist the notification
- Have `deliver_sms` decrypt and use the passed data rather than pulling it from the notification in the database

Step two // allow reports to work without phone numbers in database

- Until S3 is cleared, offer a per-batch sending report with outcomes by phone number, created by pulling the CSV from S3 and matching it with job filename and row info
- After S3 is cleared, offer only aggregate data about the batch
- At any point, offer time-delimited reports with only aggregate data

Step three // ensure that users who want it get detailed data

- Add an option during sending to receive a copy of the detailed report by email
- Create new task that pulls the detailed report and sends it to the email of the original uploader
- When a job begins with a summary requested, schedule the task for [x] hours later

Step four // remove PII from database

- Update `persist_notification` to only save allowed data
- Switch all calls to `notifications_all_time_view` to use `notifications`
- Add `QUEUED` status type for notifications and use it in `save_sms`
- Remove `notifications_all_time_view` from models
- Add migration to merge notifications tables and remove obsolete columns

**Comment by terrazoon** [comment]
Having tried the naive approach to removing the 'to' and 'normalised_to' columns from the db, I don't think it's going to work to try to do it in one fell swoop.

Instead, I think we only write the phone number on the initial create_notification call.  If we wrote "1" instead of the phone number, it would mean this would be a useless, deprecated column in the db that did not contain PII, so we could say "we don't store PII" in the db.  The purpose of writing a "1" is just to show it's been processed and we didn't forget about it.  This would allow .to and .normalised_to to stay in the model, and prevent a large number of tests from breaking (or if they break, they will break in a way that is easier to fix).  Once we achieve the goal of being able to say "we don't store PII in the db", we can always remove the columns at a later date as a technical debt task any time someone has a month of free time.

**Comment by ccostino** [comment]
Closing this issue as it was never closed!
