### ISSUE TITLE
Get sandbox environment working again

### ISSUE THREAD

**Issue by stvnrlly** [GSA/notifications-api#883]

**Comment by jskinne3** [comment]
`terraform apply` and `terraform destroy` now work in the Sandbox environment of the API codebase

**Comment by jskinne3** [comment]
✅  Sandbox environments are currently working at
* https://notify-sandbox.app.cloud.gov/
* https://notify-api-sandbox.app.cloud.gov/

To ensure they stay running:
* [ ] document errors @alexjanousekGSA and I encountered
* [ ] put routes and network policies into Terraform if possible, so that they will be re-created

**Comment by jskinne3** [comment]
With the code and documentation changes in two currently outstanding PRs ([#1779](https://github.com/GSA/notifications-admin/pull/1779) & https://github.com/GSA/notifications-api/pull/1217) Sandbox deployment works and should be a pretty greased path.

@ccostino and @ecayer I propose closing this issue.

**Comment by ccostino** [comment]
Agreed, @jskinne3!  We've tested the changes multiple times now and everything appears to be functioning properly at this point!  Thank you very much for all of the hard work here!
